version: '3.1'

services:
  db:
    image: oryxeditorextension_db
    build:
      context: ./poem-jvm
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: poem
      POSTGRES_PASSWORD: poem
      POSTGRES_DB: poem
    ports:
      - '5432:5432'
    volumes:
      - /opt/oryx/database:/var/lib/postgresql/data
    networks:
      gazelle-network:
        aliases:
          - database
  web:
    image: oryxeditorextension_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:8080'
      - '8000:8000'
    networks:
      - gazelle-network
    restart: unless-stopped
    volumes:
    - ./editor/client/scripts/Gazelle/:/usr/local/tomcat/webapps/gazelle
    - ./editor/client/scripts/Plugins/Gazelle.js:/usr/local/tomcat/webapps/plugins/Gazelle.js
networks:
  gazelle-network:
    driver: bridge
