version: '3.1'

services:
  db:
    image: oryxeditorextension_db
    build:
      context: ./poem-jvm
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./poem-jvm/db.env
    networks:
      gazelle-network:
        aliases:
          - database
    volumes:
      - ./volumes/poem-jvm/postgresql-data:/var/lib/postgresql/data
  web:
    image: oryxeditorextension_web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9090:8080'
      - '8000:8000'
    networks:
      - gazelle-network
    restart: unless-stopped
    volumes:
      - ./volumes/oryx/webapps:/usr/local/tomcat/webapps
networks:
  gazelle-network:
    driver: bridge
